### ISSUE TITLE
pdf output in script

### ISSUE THREAD

**Issue by jowens** [gunrock/io#3]
Can test_json2vega have a PDF (or SVG) output option? Again, all the complexity can/should be hidden under the hood, but that's a nice feature.

**Comment by ffarhour** [comment]
I know that I can output as SVG, not sure about pdf but should be relatively easy. I'm working on a builder model to feed the jsons to "build" the visual output.

**Comment by jowens** [comment]
SVG is fine.

**Comment by ffarhour** [comment]
SVG output has been implemented.
