### ISSUE TITLE
MapGraph output in 'topc' -- only 2 of the runs have 'elapsed' at all, making it hard to get meaningful results

### ISSUE THREAD

**Issue by jowens** [gunrock/io#30]
```
$ pwd;ls;grep elapsed *
/Users/jowens/Documents/working/gunrock-io/MapGraph-output/topc
BFS-hollywood-2009.json    PageRank-hollywood-2009.json
BFS-indochina-2004.json    PageRank-indochina-2004.json
BFS-rgg_n24_0.000548.json  PageRank-rgg_n24_0.000548.json
BFS-rmat_n22_e64.json	   PageRank-rmat_n22_e64.json
BFS-rmat_n23_e32.json	   PageRank-rmat_n23_e32.json
BFS-rmat_n24_e16.json	   PageRank-rmat_n24_e16.json
BFS-road_usa.json	   PageRank-road_usa.json
BFS-soc-LiveJournal1.json  PageRank-soc-LiveJournal1.json
BFS-soc-orkut.json	   PageRank-soc-orkut.json
CC-hollywood-2009.json	   SSSP-hollywood-2009.json
CC-indochina-2004.json	   SSSP-indochina-2004.json
CC-rgg_n24_0.000548.json   SSSP-rgg_n24_0.000548.json
CC-rmat_n22_e64.json	   SSSP-rmat_n22_e64.json
CC-rmat_n23_e32.json	   SSSP-rmat_n23_e32.json
CC-rmat_n24_e16.json	   SSSP-rmat_n24_e16.json
CC-road_usa.json	   SSSP-road_usa.json
CC-soc-LiveJournal1.json   SSSP-soc-LiveJournal1.json
CC-soc-orkut.json	   SSSP-soc-orkut.json
BFS-hollywood-2009.json:    "elapsed": 0.0,
BFS-road_usa.json:    "elapsed": 1000.0,
BFS-soc-LiveJournal1.json:    "elapsed": 0.0,
CC-hollywood-2009.json:    "elapsed": 0.0,
PageRank-hollywood-2009.json:    "elapsed": 0.0,
PageRank-road_usa.json:    "elapsed": 0.0,
PageRank-soc-LiveJournal1.json:    "elapsed": 0.0,
SSSP-hollywood-2009.json:    "elapsed": 1000.0,
```

**Comment by jowens** [comment]
Note there are 8 dots on the Tableau chart in the current paper for MapGraph and in the table as well. cc: @yzhwang

**Comment by neoblizz** [comment]
Can I get @shariiiyy input on this? She mentioned the ones that didn't have elapsed had OOM error. I can rerun the tests on my end if need be.

**Comment by jowens** [comment]
Where did @yzhwang get his numbers?

**Comment by yzhwang** [comment]
I think I reran MapGraph after @shariiiyy said she had some problem configuring the program. It's all on Mario's `/data` somewhere. I can point you guys to the exact directory once Mario is back online. I think I probably used a newer set of results than the results @neoblizz used to generate his JSON file.

**Comment by neoblizz** [comment]
@yzhwang I can remake the JSON files if you can tell me where the new results exist in `/data`.

**Comment by yzhwang** [comment]
@neoblizz Thanks! I just pinged @sgpyc to get the data asap. Will let you know once they are accessible. I'm about to generate results for both nvgraphPagerank and nvgraphSSSP. I will also let you know where they are so that you can generate JSON of those two.

**Comment by jowens** [comment]
@neoblizz Is there valid MapGraph data now?

**Comment by neoblizz** [comment]
@jowens MapGraph was never compiled on the latest CUDA, but the valid data for old CUDA version is in JSON files in io. For entries that don't have elapsed is when MapGraph failed to run.

**Comment by jowens** [comment]
OK. I will poke around then, reassigning this to me.
