### ISSUE TITLE
SSSP road_usa on v0.4, help me out?

### ISSUE THREAD

**Issue by jowens** [gunrock/io#34]
External request from an author who wants to compare against SSSP, road_usa.

We found 2 JSONs:
https://github.com/gunrock/io/blob/master/gunrock-output/topc/CentOS7.2_XXx1_topc_arch/SSSP_road_usa_Thu%20Dec%20%201%20102801%202016.json
https://github.com/gunrock/io/blob/master/gunrock-output/topc/SSSP_road_usa_Fri%20Nov%2018%20004204%202016.json

It looks like the exact same github version (and the same command line), but the timings are different enough as to make me scratch my (big bald) head. K40c vs. K40m (so the same GPU). One is consistently 9.5 seconds, one is 11 seconds. The faster one (hsw216) has

```
    "edges_queued" : 27709447,
    "edges_redundance" : 0,
```
and the slower one (luigi) has
```
    "edges_queued" : 620523505,
    "edges_redundance" : 975.26997178099407,
```

Any wisdom as to what's going on here?

**Comment by GPUGraphProcessing** [comment]
There are three versions of this file in DIMACS website with different arc weights for travel time, distance and coordinates. Are you sure you have used the same file for each?

**Comment by jowens** [comment]
We have a script that fetches the datasets so I would strongly suspect we're using a consistent dataset across all our runs.

https://github.com/gunrock/gunrock/blob/master/dataset/large/road_usa/Makefile

**Comment by sgpyc** [comment]
The file used is from http://www.cise.ufl.edu/research/sparse/matrices/DIMACS10/road_usa , it's unweighted. The program will generate a random weight for each edge in [0, 63] when first seeing the .mtx file, and store a binary version with the generated weights to a hidden file in the same directory. This may create some variance in running time, but I don't think it's the main cause for ~16% timing difference, especially for this particular dataset the running time is overhead bounded.

**Comment by jowens** [comment]
Any idea why the difference then? `edges_queued` and `edges_redundance` are pretty different.

**Comment by sgpyc** [comment]
I do rerun on the same stored graph using the same machine (luigi), on top of the master branch, and have the results below.
The main difference (today's run vs. the Nov 18 run) is the post-processing time, 1887 ms (today's run) vs. 2910 ms (the Nov 18 run). The post-processing routine is an SSSP on CPU + result comparison, such timing difference may indicate luigi's CPU was busy on Nov 18 when running this particular test, which affected the GPU SSSP timing. Today's run is almost identical to the DEC 1 run using K40m. I think we can use the Dec 1 numbers (or today's), unless more results show things closer to the Nov 18 run.

As for the edges queued, the counter is a 32-bit singed integer (SizeT), I guess it just got overflowed (in today's run, it's a negative number).

```
{
    "64bit_SizeT" : false,
    "64bit_Value" : false,
    "64bit_VertexId" : false,
    "algorithm" : "SSSP",
    "alpha" : 6,
    "average_duty" : 0,
    "beta" : 6,
    "command_line" : "./bin/sssp market /data/gunrock_dataset/large/road_usa/road_usa.mtx --src=0 --undirected --iteration-num=10 --tag=topc_arch --device=0 --traversal-mode=TWC --jsondir=./",
    "communicate_latency" : 0,
    "communicate_multipy" : -1,
    "compensate" : false,
    "compiler" : "Gnu GCC C/C++",
    "compiler_version" : 40800005,
    "dataset" : "road_usa",
    "debug_mode" : false,
    "delta" : 0.85000002384185791,
    "delta_factor" : 16,
    "destination_vertex" : 23947346,
    "device_list" : [
        0
    ],
    "direction_optimized" : false,
    "do_a" : 0.001,
    "do_b" : 0.20000000000000001,
    "duplicate_graph" : false,
    "edge_value" : true,
    "edges_queued" : -30390378,
    "edges_redundance" : 0,
    "edges_visited" : 57708624,
    "elapsed" : 9518.11328125,
    "engine" : "Gunrock",
    "error" : 0.0099999997764825821,
    "expand_latency" : 0,
    "fullqueue_latency" : 0,
    "git_commit_sha1" : "6b7b3e5fddb95feda52dfa83992c51a8e4c14663",
    "gpuinfo" : {
        "clock_rate" : 745000,
        "compute_version" : 35,
        "driver_api" : 8000,
        "driver_version" : 8000,
        "major" : 3,
        "minor" : 5,
        "multi_processor_count" : 15,
        "name" : "Tesla K40c",
        "runtime_version" : 8000,
        "total_global_mem" : 11995054080
    },
    "graph_type" : "market",
    "gunrock_version" : "0.4.0",
    "idempotent" : false,
    "instrument" : false,
    "json" : false,
    "jsondir" : "./",
    "jsonfile" : "",
    "label" : "",
    "load_time" : 1544.3811416625977,
    "m_teps" : 6.0630316734313965,
    "makeout_latency" : 0,
    "mark_predecessors" : false,
    "max_grid_size" : 0,
    "max_in_sizing" : -1,
    "max_iteration" : 50,
    "max_process_time" : 9608.4489822387695,
    "max_queue_sizing" : -1,
    "max_queue_sizing1" : -1,
    "min_process_time" : 9448.854923248291,
    "multi_graphs" : false,
    "node_value" : false,
    "nodes_queued" : 1745769775,
    "nodes_redundance" : 7190.0341528437366,
    "nodes_visited" : 23947347,
    "normalized" : false,
    "num_edges" : 57708624,
    "num_gpus" : 1,
    "num_iteration" : 10,
    "num_vertices" : 23947347,
    "output_filename" : "",
    "partition_factor" : -1,
    "partition_method" : "random",
    "partition_seed" : -1,
    "postprocess_time" : 1887.7170085906982,
    "preprocess_time" : 305.82594871520996,
    "process_times" : [
        9520.7479000091553,
        9608.4489822387695,
        9449.5398998260498,
        9554.2268753051758,
        9448.854923248291,
        9462.7711772918701,
        9592.2670364379883,
        9571.1719989776611,
        9489.3369674682617,
        9483.7710857391357
    ],
    "quick_mode" : false,
    "quiet_mode" : false,
    "random_edge_value" : false,
    "ref_filename" : "",
    "scaled" : false,
    "search_depth" : 6693,
    "size_check" : true,
    "source_list" : [
    ],
    "source_seed" : 0,
    "source_type" : "user-defined",
    "source_vertex" : 0,
    "stddev_degrees" : 0,
    "stream_from_host" : false,
    "subqueue_latency" : 0,
    "sysinfo" : {
        "machine" : "x86_64",
        "nodename" : "luigi",
        "release" : "3.13.0-106-generic",
        "sysname" : "Linux",
        "version" : "#153-Ubuntu SMP Tue Dec 6 15:44:32 UTC 2016"
    },
    "tag" : "topc_arch",
    "time" : "Wed Apr  5 09:39:46 2017\n",
    "top_nodes" : 0,
    "total_time" : 204426.12195014954,
    "traversal_mode" : "TWC",
    "undirected" : true,
    "userinfo" : {
        "login" : "sgpyc"
    },
    "write_time" : 0
}
```

**Comment by jowens** [comment]
OK. So I'll close this out, with the conclusion that the luigi run probably had CPU interference, and the 9.5 second run is more accurate.
