### ISSUE TITLE
Gunrock benchmarking for CUDA 9.0.67.

### ISSUE THREAD

**Issue by neoblizz** [gunrock/io#35]
Will push the jsons in the io repository.

**Comment by neoblizz** [comment]
@jowens results are posted (c915b9111c7c8ae391751f7866f1cfd227ffcbe9). Let me know if I need to rerun something or if there is further things to be done.

**Comment by jowens** [comment]
@neoblizz Generally these look pretty consistent, there's one weird one with SSSP for sure. Several PR runs ended up with 0 elapsed time. Can you look at those?

![cuda89](https://user-images.githubusercontent.com/976970/27557998-8b00ee72-5a70-11e7-8f00-d9baada0de38.png)

**Comment by jowens** [comment]
SSSP also had several 0 elapsed time runs.

**Comment by jowens** [comment]
And, since it's SO different, could you rerun SSSP/rgg, just to be sure?

**Comment by jowens** [comment]
@neoblizz in future runs could you please add a "tag" to any sets of runs you do? Makes it much easier to (automatically) pick out the sets of runs we want. e.g. "cuda-9-test-june-2017".

**Comment by neoblizz** [comment]
@jowens got it! I will do that for later tags. Also, I think there is a bug in LB_CULL, waiting for Yuechao to respond to the issue and I will rerun SSSP and PR. The reason why 2 PR passed was because they were using TWC not LB_CULL.

**Comment by jowens** [comment]
Understood. Any idea on the SSSP/rgg? Any idea why PR is so much faster? @sgpyc? @neoblizz is it possible to get more detailed data on those that would help @sgpyc track down what's happening? @yzhwang any chime-in here would be appreciated!

**Comment by neoblizz** [comment]
@jowens which jsons are you exactly comparing these results to? Is it `io/gunrock_output/topc`?

**Comment by jowens** [comment]
Yes, specifically the ones dated Nov 17–18 2016. (That's why we need tags, so I don't have to do weird date filtering like that.) Those are the same ones that are used in http://gunrock.github.io/gunrock/doc/latest/md_stats_engines_topc.html.

**Comment by neoblizz** [comment]
Comparison isn't proper here:

TOPC:
`../../../../gunrock_build/bin/pr market /data/Compare/topc-datasets/rgg_n24_0.000548.mtx --quick --iteration-num=10 --device=1 --jsondir=./eval/`

CUDA 9:
`../../../gunrock_build/bin/pr rgg --rgg_scale=24 --rgg_theshold=0.000548 --quick --iteration-num=10 --max-iter=1 --device=1 --traversal-mode=TWC --jsondir=./eval/`

**Comment by neoblizz** [comment]
Notice that CUDA 9 uses max iteration = 1, whereas TOPC ones, if I am looking at the right file was running for max iteration = 50.

**Comment by jowens** [comment]
At some point in the past we decided that those two RGG graphs were the same.

```
def equateRGG(df):
    df.loc[df.dataset == 'rgg_n_2_24_s0', 'dataset'] = 'rgg_n24_0.000548'
    return df
```

**Comment by jowens** [comment]
In terms of iterations, what I have is:

```
def normalizePRMTEPS(df):
    if 'search_depth' in df.columns:
        df.loc[df.algorithm == 'PageRank', 'm_teps'] = df[
            'm_teps'] * df['search_depth']
    return df
```

I should do the same thing with elapsed time then?

**Comment by neoblizz** [comment]
Yes, I can run CUDA 9 with 50 max-iter=50, just to quickly check.

**Comment by neoblizz** [comment]
It should run with max-iter=1 though, the graph here http://gunrock.github.io/gunrock/doc/latest/md_stats_engines_topc.html reflects proper data. Let me find the one where we had max-iter=1.

**Comment by neoblizz** [comment]
https://github.com/gunrock/io/blob/master/gunrock-output/topc/optimization-switch/PageRank_rgg_n24_0.000548_Tue%20Dec%20%206%20184209%202016.json

This is the correct file. Or at least one that uses same parameters as what I am using for CUDA 9 testing. And it has mteps approx same as CUDA 9's.

**Comment by jowens** [comment]
OK, replace https://github.com/gunrock/io/blob/master/gunrock-output/topc/PageRank_rgg_n24_0.000548_Thu%20Nov%2017%20232054%202016.json with https://github.com/gunrock/io/blob/master/gunrock-output/topc/optimization-switch/PageRank_rgg_n24_0.000548_Tue%20Dec%20%206%20184209%202016.json ?

**Comment by neoblizz** [comment]
Yes, please.

**Comment by sgpyc** [comment]
@neoblizz LB_CULL can't be used for PR, please change it to LB and see whether the issue is still there. I will check for LB_CULL on SSSP

**Comment by neoblizz** [comment]
@sgpyc understood, rerunning the `LB_CULL`s as `LB`s.

**Comment by jowens** [comment]
Please file an issue to make sure that `LB_CULL` flags a runtime error if used for `PR`.

**Comment by neoblizz** [comment]
@jowens similarly: replace https://github.com/gunrock/io/blob/master/gunrock-output/topc/PageRank_road_usa_Thu%20Nov%2017%20231914%202016.json#L58 with https://github.com/gunrock/io/blob/master/gunrock-output/topc/optimization-switch/PageRank_road_usa_Tue%20Dec%20%206%20184205%202016.json#L58

**Comment by neoblizz** [comment]
And for rest of the PageRank tests, use results in topc/optimization-switch with `--tag= optimization_test_LB` for CUDA 8.

**Comment by jowens** [comment]
This is an incredibly complicated thing to do given the way my code is structured. Can you simply copy all the CUDA 8 results that are relevant into the cuda9 directory and I can just use that directory straight-up?

**Comment by neoblizz** [comment]
I was actually doing that just now. Stay tuned~

**Comment by neoblizz** [comment]
@jowens:
CUDA8: https://github.com/gunrock/io/tree/master/gunrock-output/cuda8
CUDA9: https://github.com/gunrock/io/tree/master/gunrock-output/cuda9 (for SSSP and PR please use `--tag=cuda_9-0-67_june_2017`.

**Comment by neoblizz** [comment]
SSSP results still seem so weird; for example CUDA 9 on `rgg_n24_0.000548` with Traversal mode TWC yields so much better results than CUDA 8 (same settings). 

@sgpyc am I doing something wrong for rgg_n24_0.000548 test?

**Comment by jowens** [comment]
This is everything in cuda8 and cuda9.

@neoblizz 
![cuda89](https://user-images.githubusercontent.com/976970/27619253-df8b32f8-5b75-11e7-93d1-51a748109698.png)

**Comment by jowens** [comment]
@neoblizz Now using runtime version not driver version (the cuda8 PR runs were using cuda9's driver).
![cuda89](https://user-images.githubusercontent.com/976970/27619415-ef9bd62e-5b76-11e7-9b1a-80fff9ddca85.png)

**Comment by neoblizz** [comment]
@jowens I don't know if I can change the driver version:
```
mosama@mario:~$ nvidia-smi
Wed Jun 28 10:29:31 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.27                 Driver Version: 384.27                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40c          On   | 0000:02:00.0     Off |                    0 |
| 23%   37C    P8    20W / 235W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40c          On   | 0000:03:00.0     Off |                    0 |
| 23%   40C    P8    21W / 235W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN Xp            On   | 0000:83:00.0     Off |                  N/A |
| 53%   83C    P2   276W / 250W |  11862MiB / 12189MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40c          On   | 0000:84:00.0     Off |                    0 |
| 23%   39C    P8    20W / 235W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    2     21010    C   python3                                      11852MiB |
+-----------------------------------------------------------------------------+
```

```
mosama@mario:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
```

As long as I am running the correct cuda and cudart version, will it matter what driver it is? I am not sure.

**Comment by jowens** [comment]
I'll ask.

**Comment by jowens** [comment]
Slight changes with @neoblizz, not sure if they're significant.

![cuda89](https://user-images.githubusercontent.com/976970/27665929-319a524a-5c25-11e7-9791-85e0ba6a1f47.png)

**Comment by neoblizz** [comment]
@jowens I would like to point out that now these cuda 8 results are ran with the EXACT same parameters as the tests for CUDA 9. And the only thing different is that SSSP is LB_CULL (cuda 8) vs. LB (cuda 9).

**Comment by neoblizz** [comment]
BFS is the only one with significant changes.
