### ISSUE TITLE
Plot before / after cuda arch changes

### ISSUE THREAD

**Issue by crozhon** [gunrock/io#44]
I uploaded data for before and after the change I made to our launch bounds calculations. Could they be plotted to see if it had any difference? 

Before we were always assuming the compute capability was 300. This collection of JSON compares before and after the commits fixing that issue. I tagged them as

Gunrock-9c8102fa-before-use-cuda-arch
Gunrock-6ddbd33-after-use-cuda-arch

I added an INFO file with this info as well. It's all under gunrock-output/cuda_arch_comparison separated by problem and then dataset.

**Comment by jowens** [comment]
[gunrock_launch_bounds_sssp_best.pdf](https://github.com/gunrock/io/files/4107004/gunrock_launch_bounds_sssp_best.pdf)
[gunrock_launch_bounds_bfs_best.pdf](https://github.com/gunrock/io/files/4107005/gunrock_launch_bounds_bfs_best.pdf)

**Comment by jowens** [comment]
@crozhon please close this if we're done with it.
