### ISSUE TITLE
PLOT: v1+ (and if possible for older versions too, mainly 0.4+) avg-mteps

### ISSUE THREAD

**Issue by jowens** [gunrock/io#45]
avg-mteps
Not interested in any parameters used here, just plain ol' mteps and runtime for every dataset for every primitive. Tooltips are appreciated.
Note for pagerank, the time would be divided by max-iter.

**Comment by jowens** [comment]
Same thing as #46, but MTEPS. Please tell me how to fix or tell me to push to the docs.

Note the JSON has no MTEPS for `pr`; we have no data there.

![gunrock_primitives_sssp_mteps](https://user-images.githubusercontent.com/976970/81459087-eb584d80-9152-11ea-9761-d52b0f21690b.png)
![gunrock_primitives_tc_mteps](https://user-images.githubusercontent.com/976970/81459090-ee533e00-9152-11ea-992f-e6fd32101042.png)
![gunrock_primitives_bc_mteps](https://user-images.githubusercontent.com/976970/81459094-f1e6c500-9152-11ea-8ff4-bfe988239cb4.png)

**Comment by neoblizz** [comment]
Can you use the following for pagerank mteps? I will fix it in code:
```
m_teps = (double)num-edges / (elapsed * 1000.0);
```

**Comment by neoblizz** [comment]
Also, a few things:
- Does this also include Chuck's changes? So, best performance INCLUDING v1.1.x results.
- Is there a way to show this as a really long bar-chart of some sort? Or have horizontal-spacing between the GPU markers so we can see what the difference is easily?

**Comment by jowens** [comment]
This is 
```
roots = [
    "../gunrock-output/v1-0-0/sssp",
    "../gunrock-output/v1-0-0/bc",
    "../gunrock-output/v1-0-0/tc",
    "../gunrock-output/v1-0-0/pr",
    "../gunrock-output/v1-0-0/bfs",
]
```
only. If you want another directory (@crozhon's) lemme know.

**Comment by jowens** [comment]
I can fix PR MTEPS.

**Comment by jowens** [comment]
We could do a bar chart but it would be really really wide. I'll think about that!

**Comment by neoblizz** [comment]
> We could do a bar chart but it would be really really wide. I'll think about that!

I figured, but if there's a better way to add some separation to datasets and have mini plots in that giant plot. Anything that shows the difference between the GPUs is nice.

**Comment by neoblizz** [comment]
> This is
> 
> ```
> roots = [
>     "../gunrock-output/v1-0-0/sssp",
>     "../gunrock-output/v1-0-0/bc",
>     "../gunrock-output/v1-0-0/tc",
>     "../gunrock-output/v1-0-0/pr",
>     "../gunrock-output/v1-0-0/bfs",
> ]
> ```
> 
> only. If you want another directory (@crozhon's) lemme know.

Please include these:
```
gunrock-output/launch_bounds_comparison
gunrock-output/cuda_arch_comparison
```

**Comment by jowens** [comment]
OK. I'll do that for all of them. But, I'm pretty sure it's not a complete set of runs in the way that the v-1-0-0 are.

**Comment by crozhon** [comment]
Yes they are not complete sets. But everything in ‘cuda_arch_comparsion’ is in dev branch.

**Comment by neoblizz** [comment]
That's fine, we can eventually get to a complete set after all your changes are pushed @crozhon. I would just like to see the entire v1.x.x runs anyways.

**Comment by jowens** [comment]
@neoblizz My current recipe is "copy edges-queued into edges-visited, compute m-teps, then normalize runtime by the number of iterations". I assume edges-queued is global (across entire computation), not per iteration, so I need to do the m-teps compute before I normalize runtime. Tell me yea or nay.

**Comment by jowens** [comment]
So I am hoping this is good enough and I don't have to turn this into a bar. We now only have one dot per GPU. It is feasible to jitter these in x but it's more involved in terms of the programming.

PR: ![gunrock_primitives_pr_mteps](https://user-images.githubusercontent.com/976970/81485837-3c287e80-9205-11ea-944b-d4a7e1b9446b.png)
BC: ![gunrock_primitives_bc_mteps](https://user-images.githubusercontent.com/976970/81485839-3d59ab80-9205-11ea-8142-ebcd59c77be4.png)
SSSP: ![gunrock_primitives_sssp_mteps](https://user-images.githubusercontent.com/976970/81485841-3e8ad880-9205-11ea-8f78-e0027185e189.png)

**Comment by neoblizz** [comment]
> @neoblizz My current recipe is "copy edges-queued into edges-visited, compute m-teps, then normalize runtime by the number of iterations". I assume edges-queued is global (across entire computation), not per iteration, so I need to do the m-teps compute before I normalize runtime. Tell me yea or nay.

That's correct.

This looks good. Just missing BFS now.

**Comment by jowens** [comment]
Oh yeah forgot (BFS).

![gunrock_primitives_bfs_mteps](https://user-images.githubusercontent.com/976970/81488419-66863600-921d-11ea-8e54-cc3d9d177f4e.png)

**Comment by jowens** [comment]
DOBFS: ![gunrock_primitives_dobfs_mteps](https://user-images.githubusercontent.com/976970/81492389-0064d780-924c-11ea-8f27-e7ed46e4a54f.png)
BFS: ![gunrock_primitives_bfs_mteps](https://user-images.githubusercontent.com/976970/81492393-022e9b00-924c-11ea-8905-71ac3d7e20a4.png)

**Comment by neoblizz** [comment]
Also can go live! 🎉

**Comment by jowens** [comment]
Are you cool with what we have now?

**Comment by neoblizz** [comment]
Yes!
