### ISSUE TITLE
 v1+ (and if possible for older versions too, mainly 0.4+) avg-process-time

### ISSUE THREAD

**Issue by jowens** [gunrock/io#46]
avg-process-time
Not interested in any parameters used here, just plain ol' mteps and runtime for every dataset for every primitive. Tooltips are appreciated.
Note for pagerank, the time would be divided by max-iter.

**Comment by jowens** [comment]
@neoblizz : these are for the 4 app-specific `v1-0-0` directories:

![gunrock_primitives_sssp_avg-process-time](https://user-images.githubusercontent.com/976970/81459003-6c631500-9152-11ea-992f-09cf3a3ab5aa.png)
![gunrock_primitives_tc_avg-process-time](https://user-images.githubusercontent.com/976970/81459006-708f3280-9152-11ea-9ecb-990657159d9e.png)
![gunrock_primitives_bc_avg-process-time](https://user-images.githubusercontent.com/976970/81459009-771daa00-9152-11ea-99eb-6d7fc84791b7.png)
![gunrock_primitives_pr_avg-process-time](https://user-images.githubusercontent.com/976970/81459012-7c7af480-9152-11ea-9635-4537b3f73160.png)

Please let me know if those are what you are thinking. If so, I will start pushing them into the docs. Also, you want the same thing BUT also including previous < 1.0 runs? I'm a little skeptical there; I think the analysis I did for @crozhon that was specific to comparing pre-1.0 and 1.0+ is probably what we want. But I'll do what you find useful.

**Comment by jowens** [comment]
(Pushing pngs because they appear in the issue. Happy to push PDFs if you prefer those. HTML will have tooltips.)

**Comment by neoblizz** [comment]
> Please let me know if those are what you are thinking. If so, I will start pushing them into the docs. Also, you want the same thing BUT also including previous < 1.0 runs? I'm a little skeptical there; I think the analysis I did for @crozhon that was specific to comparing pre-1.0 and 1.0+ is probably what we want. But I'll do what you find useful.

These are great, but I really do prefer best results from anything >= v1.0.0, so including Chuck's analysis.
And then we can create one version of these plots which best performance from < v1.0.0 (separately, not added to the same plots).

Tooltips are great here for gunrock-devs.

**Comment by jowens** [comment]
So include ... `cuda_arch_comparison` and `launch_bounds_comparison`? @crozhon ?

**Comment by neoblizz** [comment]
Yes.

**Comment by jowens** [comment]
Are you cool with what we have now?
