### ISSUE TITLE
v1+ (and if possible for older versions too, mainly 0.4+) avg-process-time edges-visited, nodes-visited vs. num-edges, num-nodes

### ISSUE THREAD

**Issue by jowens** [gunrock/io#47]
edges-visited, nodes-visited vs. num-edges, num-nodes
For all datasets (so, the legend here is the dataset): How much "stuff" was inputted (x-axis?) vs. how much "stuff" was actually processed (y-axis?).
Note, for PR you may need to use edges-/nodes-queued instead of visited.

**Comment by jowens** [comment]
@neoblizz Not sure these are super meaningful. Perhaps some good debug info though!

![gunrock_primitives_all_vertices-visited-vs-num-vertices](https://user-images.githubusercontent.com/976970/81463429-77c43980-916e-11ea-98d1-98c87f3e5edc.png)
![gunrock_primitives_all_edges-visited-vs-num-edges](https://user-images.githubusercontent.com/976970/81463431-78f56680-916e-11ea-8bc4-16fab229fae8.png)

**Comment by jowens** [comment]
This is what a PDF attachment looks like (not inline), btw.

[gunrock_primitives_all_vertices-visited-vs-num-vertices.pdf](https://github.com/gunrock/io/files/4602596/gunrock_primitives_all_vertices-visited-vs-num-vertices.pdf)
[gunrock_primitives_all_edges-visited-vs-num-edges.pdf](https://github.com/gunrock/io/files/4602597/gunrock_primitives_all_edges-visited-vs-num-edges.pdf)

**Comment by jowens** [comment]
V100 only, probably preferable (cleaner).

![gunrock_primitives_all-V100_vertices-visited-vs-num-vertices](https://user-images.githubusercontent.com/976970/81463684-39c81500-9170-11ea-9317-e0dafe91dbb5.png)
![gunrock_primitives_all-V100_edges-visited-vs-num-edges](https://user-images.githubusercontent.com/976970/81463685-3af94200-9170-11ea-92d3-f4c444c2cff0.png)

**Comment by neoblizz** [comment]
All of the last few graphs are useful for me, is there a reason why there is no `bfs`?

**Comment by jowens** [comment]
This was under your category of "PR, SSSP, BFS and BC".

**Comment by neoblizz** [comment]
I am confused.

**Comment by jowens** [comment]
OK, when you said title "Figures for PR, SSSP, BFS and BC.", category "v1+ (and if possible for older versions too, mainly 0.4+)" at the top of https://github.com/gunrock/gunrock/issues/725, you meant also include BFS.

**Comment by jowens** [comment]
And now I see "Figures for PR, SSSP, BFS and BC" actually already includes "BFS", sooooo I'm a numbskull.

**Comment by neoblizz** [comment]
> OK, when you said title "Figures for PR, SSSP, BFS and BC.", category "v1+ (and if possible for older versions too, mainly 0.4+)" at the top of [gunrock/gunrock#725](https://github.com/gunrock/gunrock/issues/725), you meant also include BFS.

Yes, and then I made more comments that were algorithm specific plots.

**Comment by neoblizz** [comment]
After BFS, we can push these.

**Comment by jowens** [comment]
OK, I'll work on this in the morning and have a whole 'nother set for you to look at. (I have to do some data cleanup, there's some zeroes I have to track down.)

**Comment by jowens** [comment]
And now with BFS!

![gunrock_primitives_all-V100_vertices-visited-vs-num-vertices](https://user-images.githubusercontent.com/976970/81465711-d1cdfa80-9180-11ea-9ab0-56986856c99b.png)
![gunrock_primitives_all-V100_edges-visited-vs-num-edges](https://user-images.githubusercontent.com/976970/81465712-d2ff2780-9180-11ea-92fe-02fafa718de3.png)

**Comment by neoblizz** [comment]
Ok! Oh, and also can we separate `bfs` from `dobfs`? Just consider dobfs as a separate application.

**Comment by jowens** [comment]
Do we even have that distinction in 1.0+ (bfs vs dobfs)?

**Comment by jowens** [comment]
I think everything is named "bfs" at this point (the only bfs we have is dobfs).

**Comment by jowens** [comment]
![gunrock_primitives_all-V100_vertices-visited-vs-num-vertices](https://user-images.githubusercontent.com/976970/81485768-89f0b700-9204-11ea-8f5b-57726851c164.png)
![gunrock_primitives_all-V100_edges-visited-vs-num-edges](https://user-images.githubusercontent.com/976970/81485769-8b21e400-9204-11ea-8e28-e471bda49593.png)

**Comment by neoblizz** [comment]
> I think everything is named "bfs" at this point (the only bfs we have is dobfs).

dobfs is not a separate application but a flag, but what I was asking if if you could detect that flag, and name it a separate app called dobfs.

```
bfs (direction-optimized=false)
bfs (direction-optimized=true) -> rename to dobfs
bc
pr
sssp
```

**Comment by jowens** [comment]
![gunrock_primitives_all-V100_vertices-visited-vs-num-vertices](https://user-images.githubusercontent.com/976970/81492400-1e323c80-924c-11ea-9fcd-210e97681d6c.png)
![gunrock_primitives_all-V100_edges-visited-vs-num-edges](https://user-images.githubusercontent.com/976970/81492401-1f636980-924c-11ea-9025-8451c2bf5d8a.png)

**Comment by neoblizz** [comment]
They look great! Push these please.

**Comment by jowens** [comment]
Are you cool with what we have now?
