### ISSUE TITLE
 v1+ (and if possible for older versions too, mainly 0.4+) runtime vs. search-depth

### ISSUE THREAD

**Issue by jowens** [gunrock/io#48]
runtime vs. search-depth
For all datasets: number of iterations for each primitive vs. runtime or mteps (i prefer runtime).

**Comment by jowens** [comment]
@neoblizz V100 only. @Laurawly it would seem like it would be good to have a metric of search complexity in the statistics (there is no reason to put all datasets = 1, we shouldn't even have that in the JSON if it means nothing).

![gunrock_primitives_all-V100_search-depth](https://user-images.githubusercontent.com/976970/81463737-9fb49c80-9170-11ea-90db-48ef0506ab2d.png)

**Comment by neoblizz** [comment]
I believe some algorithms only have `search-depth = 1`, which is fine. It should still tell us that it is search depth 1.

**Comment by jowens** [comment]
Now with BFS!

![gunrock_primitives_all-V100_search-depth](https://user-images.githubusercontent.com/976970/81465695-a6e3a680-9180-11ea-9e2b-14b9238edf15.png)

**Comment by jowens** [comment]
https://gunrock.github.io/docs/#/analysis/results_search_depth

Does this give you what you need?
