### ISSUE TITLE
test_json2vega needs guidance on its arguments rather than throwing an error

### ISSUE THREAD

**Issue by jowens** [gunrock/io#5]
```
$ ./test_json2vega.py
Traceback (most recent call last):
  File "./test_json2vega.py", line 42, in <module>
    main(sys.argv)
  File "./test_json2vega.py", line 22, in main
    args = parseCmdLineArgs(argv)  # process input arguments passed
TypeError: parseCmdLineArgs() takes exactly 3 arguments (1 given)
```

**Comment by ffarhour** [comment]
Yes, I should fix this. Now, with create_graph.py I don't think test_json2vega.py will be necessary. I may  still fix this to help anyone wishing to work on the code.

**Comment by jowens** [comment]
If it's not necessary, then delete it. We can always get it back from source control.

**Comment by ffarhour** [comment]
deleted test_json2vega.py 
commit:  ca1daac6a31ad20d2b2ba958a710ab71e3bc0d7c
