### ISSUE TITLE
 BFS: do_a and do_b heatmap

### ISSUE THREAD

**Issue by jowens** [gunrock/io#52]
do_a and do_b heatmap
I want to regenerate a heatmap like this: http://gunrock.github.io/gunrock/doc/latest/md_stats_do_ab_random.html with v1+ code and have it be side-by-side to the older heatmap. This requires generating some data using a simple script.

**Comment by jowens** [comment]
@neoblizz : do we have any data for do_a and do_b that I can use?

**Comment by neoblizz** [comment]
Can you use the older JSONs for this for now? https://github.com/gunrock/io/tree/master/gunrock-output/topc/BFS.CentOS7.2_k40cx1_do_sweep2 The schema would change, but what I will generate for the new ones would be pretty much the same.

**Comment by jowens** [comment]
We already have this though:

https://gunrock.github.io/gunrock/doc/latest/md_stats_do_ab_random

What would be different?

**Comment by neoblizz** [comment]
Well no, it's the same thing. Do you have to update the scripts to reproduce that? I'll generate updated results this week for both this issue and issue #57.

**Comment by jowens** [comment]
I don't see that we have to update anything, do we? It's already published, it looks fine to me ...

**Comment by neoblizz** [comment]
Old one is fine. I would love `viridis` color scheme on the new one when we generate that.

**Comment by jowens** [comment]
If you generate new data, I'll generate a new set of graphs, and use viridis. Probably not worth it to overhaul the old scripts just to put it in the new format.

**Comment by neoblizz** [comment]
Just to get things started, one dataset is finished for 1.x.x: https://github.com/gunrock/io/tree/master/gunrock-output/v1-0-0/dobfs_parameter_sweep

Rest are still running and I will add them to the same folder under their respective dataset name.

**Comment by jowens** [comment]
Unassigning myself until we get more data.

**Comment by neoblizz** [comment]
https://github.com/gunrock/io/tree/master/gunrock-output/v1-0-0/dobfs_parameter_sweep more data.
I am having issues with the rmat generator, so the last 2 graphs will be added later.

**Comment by jowens** [comment]
![gunrock_dobfs_heatmaps_soc-LiveJournal1_do_ab](https://user-images.githubusercontent.com/976970/86540434-24ded800-beba-11ea-86bd-2613a211f2e3.png)
![gunrock_dobfs_heatmaps_hollywood-2009_do_ab](https://user-images.githubusercontent.com/976970/86540435-26100500-beba-11ea-89d5-b580cb39197e.png)
![gunrock_dobfs_heatmaps_road_usa_do_ab](https://user-images.githubusercontent.com/976970/86540436-26a89b80-beba-11ea-87f4-f1c7d6ba0686.png)
![gunrock_dobfs_heatmaps_rmat_n24_e16 000000_do_ab](https://user-images.githubusercontent.com/976970/86540437-27d9c880-beba-11ea-99e6-fc4c36931442.png)
![gunrock_dobfs_heatmaps_indochina-2004_do_ab](https://user-images.githubusercontent.com/976970/86540438-27d9c880-beba-11ea-9d19-bca634832ecc.png)
![gunrock_dobfs_heatmaps_soc-orkut_do_ab](https://user-images.githubusercontent.com/976970/86540439-27d9c880-beba-11ea-80b3-c29e009d5395.png)

**Comment by neoblizz** [comment]
Thank you, these are really cool to see. These can go live on the site.

**Comment by neoblizz** [comment]
rmats are very similar, so I am only doing one of those. Closing this.
