### ISSUE TITLE
 PR only: Comparing push vs. pull

### ISSUE THREAD

**Issue by jowens** [gunrock/io#56]
Comparing push vs. pull
I would like to see a comparison of search-depth (this maybe the same), runtime/mteps, edges-queued, nodes-queued

**Comment by jowens** [comment]
@neoblizz

**Comment by jowens** [comment]
![gunrock_primitives_pr_push_pull_avg_process_time](https://user-images.githubusercontent.com/976970/83211882-0cd5a500-a113-11ea-92f7-0ecd9b9cbe53.png)
![gunrock_primitives_pr_push_pull_edges_visited](https://user-images.githubusercontent.com/976970/83211887-0e06d200-a113-11ea-86fd-13f8f9f59767.png)
![gunrock_primitives_pr_push_pull_mteps](https://user-images.githubusercontent.com/976970/83211889-0f37ff00-a113-11ea-8f29-14cc54c777a6.png)
![gunrock_primitives_pr_push_pull_search_depth](https://user-images.githubusercontent.com/976970/83211890-0fd09580-a113-11ea-8a9d-c022e3a1a1b8.png)
![gunrock_primitives_pr_push_pull_vertices_visited](https://user-images.githubusercontent.com/976970/83211891-0fd09580-a113-11ea-9cda-ab6be590bdd6.png)

**Comment by jowens** [comment]
summary AFAICT: runtimes/MTEPS differ; search depth, vertices/edges visited do not.

**Comment by neoblizz** [comment]
Ok, good to know.

One minor code related takeaway from this is to move primitive specific json stats into the actual primitive files. We don't do a good job at this because some apps have that in rapidjson_info.cuh and others do it within the app.

I am closing this.

**Comment by jowens** [comment]
Yeah, I put a note about that the other day in the JSON guidance doc on the wiki. (In this case, `pull` should only be in the PR JSON files and not a field in anything else.)
