### ISSUE TITLE
methodology for ignoring short runs

### ISSUE THREAD

**Issue by jowens** [gunrock/io#64]
We ignore short runs (those that have a runtime that's shorter than, IIRC, a standard deviation less than the mean? or something like that. I want to put this on the methodology page. @neoblizz can you provide a pointer to where the code is and I'll write it up? No hurry.

**Comment by neoblizz** [comment]
https://github.com/gunrock/gunrock/blob/master/gunrock/util/info_rapidjson.cuh#L612-L660

And I am using two times the standard deviation:

```
      auto lower_limit = elapsed - (2*stddev_process_time);
      auto upper_limit = elapsed + (2*stddev_process_time);
```
