### ISSUE TITLE
Change create_graph into a modularized script

### ISSUE THREAD

**Issue by ffarhour** [gunrock/io#9]
So have it as a standalone file while being able to import it and run it in other python scripts. 

Would needd a call that takes a dictionary as an argument, such that the dictionary contains all the equivalent commandline arguments that would normally be passed to the argument. 

Purpose: to be able to build a bunch of graphs at the same time.

**Comment by jowens** [comment]
This is the most important issue for me, because I can at least start assembling multiple calls from a single python script into your "create_graph" library call once this is done. Thanks!
